services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dtlabs-backend
    labels:
      - "author=Miguel Batista"
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV=Docker
    depends_on:
      - db
    networks:
      - dtlabs-network
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:15-alpine
    container_name: dtlabs-postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dtlabs-network

networks:
  dtlabs-network:
    driver: bridge

volumes:
  postgres_data:
