services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dtlabs-backend

    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV=Docker
    depends_on:
      - db
    networks:
      - dtlabs-network
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
  
  api_consumer:
    build:
      context: api_consumer
      dockerfile: Dockerfile
    container_name: dtlabs-api-consumer
    networks:
      - dtlabs-network
    depends_on:
      - app
      - db
    environment:
     - API_URL=host.docker.internal:8000   # Use o nome do serviço "app" para se referir ao endereço do backend

  db:
    image: postgres:15-alpine
    container_name: dtlabs-postgres
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dtlabs-network

networks:
  dtlabs-network:
    driver: bridge



volumes:
  postgres_data:
